#include <iostream>
#include <unordered_map>
#include <string>
#include "bcrypt.h"

// simple program that checks a username and password
// it's trying to be secure, but it can easy hack use tools like ghidra

int main() {
    std::unordered_map<std::string, std::string> users;

    // hash was generated by bcrypt::generateHash()
    //     std::string password = "mypswd123";
    //     std::string hash = bcrypt::generateHash(password);
    users["user"] = "$2b$10$GUKXLHtd134NCwoMcmjMxORXLeMI2wv2nPs7KT70UQgk1QpHHIrmG";
    
    int loginAttempts = 0;
    const int maxLoginAttempts = 3;

    while (true) {
        std::string username, password;
        
        std::cout << "Enter username: ";
        std::cin >> username;
        
        std::cout << "Enter password: ";
        std::cin >> password;
        
        if (users.find(username) != users.end()) {
          std::string passwordHash = users[username];
            
            if (bcrypt::validatePassword(password, passwordHash)) {
                std::cout << "Access granted!\n";
                break;
            } else {
                std::cout << "Access denied!\n";
                loginAttempts++;
                
                if (loginAttempts >= maxLoginAttempts) {
                    std::cout << "Maximum login attempts reached. Exiting.\n";
                    break;
                }
            }
        } else {
            std::cout << "User not found!\n";
        }
    }
    
    return 0;
}
